---

# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # assignees:
      #   - "@opencpk/opencpk-admins"
      # group name used in pull request titles and branch names
      ghactions-version-updates:
        applies-to: version-updates
        # A wildcard that matches all dependencies in the package ecosystem.
        patterns:
          - "*"
        exclude-patterns:
          - "somepattern"
