---

################################
# See https://pre-commit.com for more information - see https://pre-commit.com/hooks.html for more hooks
################################

repos:
  # -----------------------------
  # Check if upstream and sync if necessary
  # -----------------------------
  - repo: git@github.com:opencpk/opencpk-lib-shell-common.git
    rev: v2.0.0
    hooks:
      - id: git-upstream-sync
        name: git-upstream-sync
        pass_filenames: false
  # -----------------------------
  # set up commit message hook
  # -----------------------------
  - repo: git@github.com:opencpk/opencpk-lib-shell-common.git
    rev: v2.0.0
    hooks:
      - id: setup-commit-msg-hook
        name: setup-commit-msg-hook
        pass_filenames: false
  # -----------------------------
  # Replace placeholders in template files with values for your project
  # -----------------------------
  - repo: git@github.com:opencpk/opencpk-lib-python-common.git
    rev: v1.0.1
    hooks:
      - id: find-and-replace-strings
        args: ["--config", "./.project-properties.json"]
        pass_filenames: true
        exclude: ^.git|^.*\.project-properties.yaml$
        exclude_types:
          - binary
        files: .
  # -----------------------------
  # Standard pre-commit-hooks for general all-purpose formatting and validation
  # -----------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  # -----------------------------
  # Gitleaks SAST tool for detecting and preventing hardcoded secrets like passwords, api keys, and tokens in git repos
  # -----------------------------
  # If you are knowingly committing something that is not a secret and gitleaks is catching it,
  # you can add an inline comment of '# gitleaks:allow' to the end of that line in your file.
  # This will instructs gitleaks to ignore that secret - example:
  #   some_non_secret_value = a1b2c3d4e5f6g7h8i9j0 # gitleaks:allow
  # -----------------------------
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  # -----------------------------
  # Generates Table of Contents in Markdown files
  # -----------------------------
  - repo: https://github.com/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        args: [-p, github]  # CLI options
  # -----------------------------
  # YAML Linting on yaml files for pre-commit and github actions
  # -----------------------------
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: Check YAML syntax with yamllint
        args: [--strict, -c=.yamllint.yaml, '.']
        always_run: true
        pass_filenames: true
  # -----------------------------
  # GitHub Actions Workflow Linting on .github/workflows/*.yml files
  # -----------------------------
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
  # -----------------------------
  # Pre Commit Template - Skip Hooks - Cleanup
  # -----------------------------
  - repo: local
    hooks:
      - id: pre-commit-template-skip-hooks-cleanup
        name: pre-commit-template-skip-hooks-cleanup
        language: system
        entry: assets/scripts/pre-commit-template-skip-hooks-cleanup.sh
        pass_filenames: false
        files: .pre-commit-template-skip-hooks.sh
