---
name: 'github-flow-commit-message-validation'
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  github-commit-message-validation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_READONLY_ACCESS_TO_MODULES }}

      - name: github-flow-check-commit-message
        uses: opencpk/opencpk-module-ghactions-common/github-flow-check-commit-message@main
        with:
          commit-pattern: '^(feat|fix|build|breaking|chore|ci|docs|perf|refactor|revert|test)\/([\w-]+)*(:\s+)?(.+)?$'
