---
name: 'github-flow-pr-title-update'
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  github-pr-title-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: github-flow-check-branch-name
        uses: opencpk/opencpk-module-ghactions-common/github-flow-check-branch-name@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: github-flow-update-pr-title
        uses: opencpk/opencpk-module-ghactions-common/github-flow-update-pr-title@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
