---
name: github-call-set-topic
on:
  push:
    branches:
      - main

jobs:
  call-set-topic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.GH_APP_REPO_ACTION_RW_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APP_REPO_ACTION_RW_PRIVATE_KEY }}
          revoke_token: true

      - name: Read and Stringify JSON Data
        id: read-and-stringify-json
        uses: opencepk/opencepk-module-ghactions-common/read-and-stringify-json-action@main
        with:
          file: '.project-properties.json'
          file_type: 'json'

      - name: Debug Stringified JSON Data
        run: |
          echo "JSON Data which will be sent: ${{ steps.read-and-stringify-json.outputs.output }}"

      - name: Trigger reusable workflow via API
        uses: opencepk/opencepk-module-ghactions-common/trigger-workflow-action@main
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          repo: 'opencepk/opencepk-projects-hub'
          workflow_id: 'github-set-topic-workflow.yml'
          ref: 'main'
          inputs: '{"repo":"${{github.repository}}","properties":"${{ steps.read-and-stringify-json.outputs.output}}"}'
