---
name: 'gitops-gh-release-automation'
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  gitops-gh-release-automation:
    runs-on: ubuntu-latest
    environment:
      name: Semver
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_READONLY_ACCESS_TO_MODULES }}

      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          extra_plugins: |
           conventional-changelog-conventionalcommits@8.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: gitops-gh-update-release-notes
        uses: opencpk/opencpk-module-ghactions-common/github-flow-update-release-notes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
